name: Sync upstream
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Sync from upstream
        run: |
          git remote add upstream https://www.bearssl.org/git/BearSSL
          git fetch upstream --tags
          git push origin upstream/master:master --tags
